-- Seed, cargado por `npx supabase db reset` en local, o aplicado a un
-- proyecto remoto con `npx supabase db push` / `db query -f`.
--
-- Este archivo se genera con:
--   python3 mock/generar_seed.py > supabase/seed.sql
-- desde mock/*.json. No se edita a mano.

-- === 03-catalogo-productos ===
-- 16 categorias, 328 productos (ver mock/README.md).

insert into public.categoria (id, nombre, matiz, unidad_negocio, orden) values
  ('viveres', 'Viveres', 60, 'bodega'::unidad_negocio, 1),
  ('granos', 'Granos', 265, 'bodega'::unidad_negocio, 2),
  ('enlatados', 'Enlatados', 265, 'bodega'::unidad_negocio, 3),
  ('condimentos', 'Condimentos', 265, 'bodega'::unidad_negocio, 4),
  ('charcuteria-y-proteinas', 'Charcuteria y proteinas', 200, 'bodega'::unidad_negocio, 5),
  ('bebidas', 'Bebidas', 240, 'bodega'::unidad_negocio, 6),
  ('higiene-y-limpieza', 'Higiene y limpieza', 175, 'bodega'::unidad_negocio, 7),
  ('otros-articulos', 'Otros articulos', 265, 'bodega'::unidad_negocio, 8),
  ('galletas', 'Galletas', 265, 'bodega'::unidad_negocio, 9),
  ('wafers', 'Wafers', 265, 'bodega'::unidad_negocio, 10),
  ('snacks', 'Snacks', 330, 'bodega'::unidad_negocio, 11),
  ('chocolates', 'Chocolates', 265, 'bodega'::unidad_negocio, 12),
  ('caramelos', 'Caramelos', 265, 'bodega'::unidad_negocio, 13),
  ('chicles', 'Chicles', 265, 'bodega'::unidad_negocio, 14),
  ('gomitas', 'Gomitas', 265, 'bodega'::unidad_negocio, 15),
  ('tortas-y-panques', 'Tortas y panques', 40, 'bodega'::unidad_negocio, 16)
on conflict (id) do update set
  nombre = excluded.nombre,
  matiz = excluded.matiz,
  unidad_negocio = excluded.unidad_negocio,
  orden = excluded.orden;

insert into public.producto
  (sku, nombre, categoria_id, unidad_negocio, unidad_medida,
   precio_venta_usd, costo_usd, stock_actual, stock_minimo, activo, origen)
values
  ('harina-p-a-n', 'Harina P.A.N', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.57, null, 21.0, 5, true, 'BODEGA!B4'),
  ('harina-mary', 'Harina Mary', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 20.0, 5, true, 'BODEGA!B5'),
  ('harina-de-trigo', 'Harina De Trigo', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.6, null, 8.0, 5, true, 'BODEGA!B6'),
  ('arroz-mary-esmeralda', 'Arroz Mary Esmeralda', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.1, null, 8.0, 5, true, 'BODEGA!B7'),
  ('arroz-mary-tradicional', 'Arroz Mary Tradicional', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 7.0, 5, true, 'BODEGA!B8'),
  ('arroz-kaly', 'Arroz Kaly', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 7.0, 5, true, 'BODEGA!B9'),
  ('pasta-corta-1-2-ronco', 'Pasta Corta 1/2 Ronco', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 0.0, 5, true, 'BODEGA!B10'),
  ('pasta-corta-1-2-mary', 'Pasta Corta 1/2 Mary', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 10.0, 5, true, 'BODEGA!B11'),
  ('pasta-corta-1-2-galo', 'Pasta Corta 1/2 Galo', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 0.0, 5, true, 'BODEGA!B12'),
  ('pasta-larga-1-2-galo', 'Pasta Larga 1/2 Galo', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 7.0, 5, true, 'BODEGA!B13'),
  ('azucar', 'Azucar', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.8, null, 7.0, 5, true, 'BODEGA!B14'),
  ('azucar-detallada-180g', 'Azucar Detallada 180G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.4, null, 1.0, 5, true, 'BODEGA!B15'),
  ('sal', 'Sal', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.65, null, 10.0, 5, true, 'BODEGA!B16'),
  ('sal-cruz-de-oro', 'Sal Cruz De Oro', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.65, null, 7.0, 5, true, 'BODEGA!B17'),
  ('mezcla-cachapas', 'Mezcla Cachapas', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.0, null, 8.0, 5, true, 'BODEGA!B18'),
  ('mezcla-para-torta', 'Mezcla Para Torta', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 9.0, 5, true, 'BODEGA!B19'),
  ('leche-los-andes', 'Leche Los Andes', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.8, null, 0.0, 5, true, 'BODEGA!B20'),
  ('leche-upaca', 'Leche Upaca', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 12.0, 5, true, 'BODEGA!B21'),
  ('avena-pq', 'Avena Pq', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 0.0, 5, true, 'BODEGA!B22'),
  ('avena-gd', 'Avena Gd', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 0.0, 5, true, 'BODEGA!B23'),
  ('crema-de-arroz', 'Crema De Arroz', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 6.0, 5, true, 'BODEGA!B24'),
  ('maizina', 'Maizina', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 9.0, 5, true, 'BODEGA!B25'),
  ('cafe-amanecer-pq', 'Café Amanecer Pq', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 12.0, 5, true, 'BODEGA!B26'),
  ('cafe-amanecer-grande', 'Café Amanecer Grande', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.3, null, 12.0, 5, true, 'BODEGA!B27'),
  ('cafe-san-domingo-pq', 'Café San Domingo Pq', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 0.0, 5, true, 'BODEGA!B28'),
  ('aceite-vatel', 'Aceite Vatel', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 5.5, null, 8.0, 5, true, 'BODEGA!B29'),
  ('aceite-coposa-y-amacorp', 'Aceite Coposa Y Amacorp', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.2, null, 9.0, 5, true, 'BODEGA!B30'),
  ('aceite-pampa-500ml', 'Aceite Pampa 500Ml', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 6.0, 5, true, 'BODEGA!B31'),
  ('acete-ideal-250-ml', 'Acete Ideal 250 Ml', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.8, null, 0.0, 5, true, 'BODEGA!B32'),
  ('acete-ideal-110-ml', 'Acete Ideal 110 Ml', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.65, null, 19.0, 5, true, 'BODEGA!B33'),
  ('vinagre', 'Vinagre', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 22.0, 5, true, 'BODEGA!B34'),
  ('salsa-inglesa', 'Salsa Inglesa', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 10.0, 5, true, 'BODEGA!B35'),
  ('salsa-de-ajo', 'Salsa De Ajo', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 14.0, 5, true, 'BODEGA!B36'),
  ('salsa-de-soya', 'Salsa De Soya', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.7, null, 12.0, 5, true, 'BODEGA!B37'),
  ('salsa-pizza', 'Salsa Pizza', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 5.0, 5, true, 'BODEGA!B38'),
  ('salsa-bolonesa', 'Salsa Boloñesa', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 7.0, 5, true, 'BODEGA!B39'),
  ('salsa-de-tomate-198g', 'Salsa De Tomate 198G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.55, null, 6.0, 5, true, 'BODEGA!B40'),
  ('salsa-de-tomate-397g', 'Salsa De Tomate 397G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.3, null, 10.0, 5, true, 'BODEGA!B41'),
  ('salsa-de-tomate-osole', 'Salsa De Tomate Osole', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 5.0, 5, true, 'BODEGA!B42'),
  ('mostaza-sobre', 'Mostaza Sobre', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 5.0, 5, true, 'BODEGA!B43'),
  ('mostaza-eureka', 'Mostaza Eureka', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.35, null, 0.0, 5, true, 'BODEGA!B44'),
  ('mayonesa-175g', 'Mayonesa 175G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 7.0, 5, true, 'BODEGA!B45'),
  ('mayonesa-445g', 'Mayonesa 445G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.9, null, 5.0, 5, true, 'BODEGA!B46'),
  ('mantequilla-250g', 'Mantequilla 250G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.1, null, 12.0, 5, true, 'BODEGA!B47'),
  ('mantequilla-500g', 'Mantequilla 500G', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.6, null, 5.0, 5, true, 'BODEGA!B48'),
  ('mantequilla-deline', 'Mantequilla Deline', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 10.0, 5, true, 'BODEGA!B49'),
  ('kellogs-zucaritas', 'Kellogs Zucaritas', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.55, null, 0.0, 5, true, 'BODEGA!B50'),
  ('kellogs-chocozucaritas', 'Kellogs Chocozucaritas', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.55, null, 0.0, 5, true, 'BODEGA!B51'),
  ('kellogs-chocokrispis', 'Kellogs Chocokrispis', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 5.7, null, 0.0, 5, true, 'BODEGA!B52'),
  ('kellogs-corn-flakes', 'Kellogs Corn Flakes', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.25, null, 0.0, 5, true, 'BODEGA!B53'),
  ('maizoritos-cronch', 'Maizoritos Cronch', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.4, null, 0.0, 5, true, 'BODEGA!B54'),
  ('maizoritos-azucaradas', 'Maizoritos Azucaradas', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.5, null, 0.0, 5, true, 'BODEGA!B55'),
  ('maizoritos-abci', 'Maizoritos Abci', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.25, null, 0.0, 5, true, 'BODEGA!B56'),
  ('leche-condensada', 'Leche Condensada', 'viveres', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.75, null, 0.0, 5, true, 'BODEGA!B57'),
  ('maiz-cotufas', 'Maiz Cotufas', 'granos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 6.0, 5, true, 'BODEGA!B59'),
  ('arvejas-400g', 'Arvejas 400G', 'granos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 6.0, 5, true, 'BODEGA!B60'),
  ('caraotas-400g', 'Caraotas 400G', 'granos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.93, null, 6.0, 5, true, 'BODEGA!B61'),
  ('lentejas-900g', 'Lentejas 900G', 'granos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.93, null, 3.0, 5, true, 'BODEGA!B62'),
  ('diablito-54g', 'Diablito 54G', 'enlatados', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 13.0, 5, true, 'BODEGA!B66'),
  ('atun', 'Atun', 'enlatados', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 13.0, 5, true, 'BODEGA!B67'),
  ('sardina', 'Sardina', 'enlatados', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 13.0, 5, true, 'BODEGA!B68'),
  ('pepitona', 'Pepitona', 'enlatados', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 13.0, 5, true, 'BODEGA!B69'),
  ('rikesa', 'Rikesa', 'enlatados', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.5, null, 12.0, 5, true, 'BODEGA!B70'),
  ('sopa-maggi', 'Sopa Maggi', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 11.0, 5, true, 'BODEGA!B72'),
  ('cubito-maggi', 'Cubito Maggi', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.28, null, 75.0, 5, true, 'BODEGA!B73'),
  ('cubito-laila', 'Cubito Laila', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.09, null, 0.0, 5, true, 'BODEGA!B74'),
  ('sabroseador', 'Sabroseador', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.63, null, 15.0, 5, true, 'BODEGA!B75'),
  ('caldo-de-ajo', 'Caldo De Ajo', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.7, null, 14.0, 5, true, 'BODEGA!B76'),
  ('adobo-ole', 'Adobo Ole', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 19.0, 5, true, 'BODEGA!B77'),
  ('adobo', 'Adobo', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 23.0, 5, true, 'BODEGA!B78'),
  ('color', 'Color', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 22.0, 5, true, 'BODEGA!B79'),
  ('carmencita', 'Carmencita', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 23.0, 5, true, 'BODEGA!B80'),
  ('comino', 'Comino', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B81'),
  ('pimienta-negra', 'Pimienta Negra', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B82'),
  ('oregano', 'Oregano', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 20.0, 5, true, 'BODEGA!B83'),
  ('curry', 'Curry', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B84'),
  ('paprika', 'Paprika', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B85'),
  ('salsa-para-pasta', 'Salsa Para Pasta', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B86'),
  ('sabroseador-2', 'Sabroseador', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B87'),
  ('ajo-cebolla-y-perejil', 'Ajo,Cebolla Y Perejil', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B88'),
  ('laurel', 'Laurel', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B89'),
  ('anis-dulce', 'Anis Dulce', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B90'),
  ('clavo-de-olor', 'Clavo De Olor', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B91'),
  ('manzanila', 'Manzanila', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B92'),
  ('torongil', 'Torongil', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B93'),
  ('malojillo', 'Malojillo', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B94'),
  ('canela-polvo', 'Canela Polvo', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.36, null, 0.0, 5, true, 'BODEGA!B95'),
  ('canela-palo', 'Canela Palo', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.57, null, 0.0, 5, true, 'BODEGA!B96'),
  ('bicarbonato', 'Bicarbonato', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.34, null, 0.0, 5, true, 'BODEGA!B97'),
  ('vainilla', 'Vainilla', 'condimentos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 0.0, 5, true, 'BODEGA!B98'),
  ('huevo-und', 'Huevo Und', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.27, null, 0.0, 5, true, 'BODEGA!B100'),
  ('huevo-1-2', 'Huevo 1/2', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.0, null, 9.0, 5, true, 'BODEGA!B101'),
  ('huevo-carton', 'Huevo Carton', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 6.0, null, 10.0, 5, true, 'BODEGA!B102'),
  ('queso-duro', 'Queso Duro', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 8.0, null, 0.0, 1, true, 'BODEGA!B103'),
  ('queso-paisa', 'Queso Paisa', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 12.0, null, 0.0, 1, true, 'BODEGA!B104'),
  ('queso-mozarella', 'Queso Mozarella', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 11.0, null, 0.0, 1, true, 'BODEGA!B105'),
  ('queso-amarillo', 'Queso Amarillo', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 12.0, null, 2.6, 1, true, 'BODEGA!B106'),
  ('jamon', 'Jamon', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 10.0, null, 0.0, 1, true, 'BODEGA!B107'),
  ('mortadela-giacomelo', 'Mortadela Giacomelo', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 10.0, null, 4.4, 1, true, 'BODEGA!B108'),
  ('salchicha-tipo-polaca', 'Salchicha Tipo Polaca', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 1.0, null, 0.0, 1, true, 'BODEGA!B109'),
  ('pollo-alas', 'Pollo Alas', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 4.5, null, 0.0, 1, true, 'BODEGA!B110'),
  ('pollo-muslo', 'Pollo Muslo', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 4.0, null, 0.0, 1, true, 'BODEGA!B111'),
  ('chuleta-ahumada', 'Chuleta Ahumada', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 9.0, null, 0.0, 1, true, 'BODEGA!B112'),
  ('carne-molida', 'Carne Molida', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 12.0, null, 0.0, 1, true, 'BODEGA!B113'),
  ('bistec', 'Bistec', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 13.0, null, 0.0, 1, true, 'BODEGA!B114'),
  ('masa-facil', 'Masa Facil', 'charcuteria-y-proteinas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 3.0, 5, true, 'BODEGA!B115'),
  ('choco-listo', 'Choco Listo', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.47, null, 12.0, 5, true, 'BODEGA!B117'),
  ('toddy', 'Toddy', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 0.0, 5, true, 'BODEGA!B118'),
  ('gelatina-polvo', 'Gelatina Polvo', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 4.0, 5, true, 'BODEGA!B119'),
  ('panelada', 'Panelada', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.53, null, 16.0, 5, true, 'BODEGA!B120'),
  ('boka', 'Boka', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.45, null, 17.0, 5, true, 'BODEGA!B121'),
  ('compota-pq', 'Compota Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.68, null, 14.0, 5, true, 'BODEGA!B122'),
  ('compota-gd', 'Compota Gd', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.9, null, 0.0, 5, true, 'BODEGA!B123'),
  ('gelatina', 'Gelatina', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 7.0, 5, true, 'BODEGA!B124'),
  ('mi-gurt', 'Mi Gurt', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 18.0, 5, true, 'BODEGA!B125'),
  ('yogurt-griego', 'Yogurt Griego', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.0, null, 4.0, 5, true, 'BODEGA!B126'),
  ('yogurt-griego-pq', 'Yogurt Griego Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 0.0, 5, true, 'BODEGA!B127'),
  ('leche-liquida-1l', 'Leche Liquida 1L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.5, null, 5.0, 5, true, 'BODEGA!B128'),
  ('chicha-pq', 'Chicha Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 0.0, 5, true, 'BODEGA!B129'),
  ('chocoya', 'Chocoya', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.13, null, 0.0, 5, true, 'BODEGA!B130'),
  ('jugo-fruttsi', 'Jugo Fruttsi', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'BODEGA!B131'),
  ('jugo-mamilo', 'Jugo Mamilo', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'BODEGA!B132'),
  ('jugo-natulac-330-m', 'Jugo Natulac 330 M', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.38, null, 8.0, 5, true, 'BODEGA!B133'),
  ('jugo-natulac-250-pq', 'Jugo Natulac 250 Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 4.0, 5, true, 'BODEGA!B134'),
  ('jugo-natulac-tripac-3-250', 'Jugo Natulac Tripac (3) 250', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.8, null, 4.0, 5, true, 'BODEGA!B135'),
  ('jugo-natulac-1l', 'Jugo Natulac 1L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.7, null, 12.0, 5, true, 'BODEGA!B136'),
  ('jugo-dafruta-250-pq', 'Jugo Dafruta 250 Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.8, null, 11.0, 5, true, 'BODEGA!B137'),
  ('jugo-dafruta-1litro', 'Jugo Dafruta 1Litro', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 0.0, 5, true, 'BODEGA!B138'),
  ('yukery-botella-pq', 'Yukery Botella Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 24.0, 5, true, 'BODEGA!B139'),
  ('yukery-naranja-1-1-2-l', 'Yukery Naranja 1 1/2 L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 5.5, null, 6.0, 5, true, 'BODEGA!B140'),
  ('yukery-durazno-1-1-2-l', 'Yukery Durazno 1 1/2 L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 5.3, null, 6.0, 5, true, 'BODEGA!B141'),
  ('justy-pq', 'Justy Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.6, null, 0.0, 5, true, 'BODEGA!B142'),
  ('justy-gd', 'Justy Gd', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.4, null, 0.0, 5, true, 'BODEGA!B143'),
  ('jugo-jucosa-pq', 'Jugo Jucosa Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.69, null, 0.0, 5, true, 'BODEGA!B144'),
  ('jugo-frica-pq', 'Jugo Frica Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 24.0, 5, true, 'BODEGA!B145'),
  ('malta-pq', 'Malta Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.65, null, 21.0, 5, true, 'BODEGA!B146'),
  ('malta-1-5l', 'Malta 1.5L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 11.0, 5, true, 'BODEGA!B147'),
  ('agua-pq-400ml', 'Agua Pq 400Ml', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.3, null, 35.0, 5, true, 'BODEGA!B148'),
  ('agua-mediana-600ml', 'Agua Mediana 600Ml', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.44, null, 0.0, 5, true, 'BODEGA!B149'),
  ('agua-grande', 'Agua Grande', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 11.0, 5, true, 'BODEGA!B150'),
  ('agua-gasificada-pq', 'Agua Gasificada Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.82, null, 0.0, 5, true, 'BODEGA!B151'),
  ('agua-gasificada-1-1-2-l', 'Agua Gasificada 1 1/2 L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 0.0, 5, true, 'BODEGA!B152'),
  ('spedd', 'Spedd', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.76, null, 15.0, 5, true, 'BODEGA!B153'),
  ('gatorade', 'Gatorade', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.63, null, 15.0, 5, true, 'BODEGA!B154'),
  ('refresco-botella', 'Refresco Botella', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.71, null, 28.0, 5, true, 'BODEGA!B155'),
  ('refresco-surtido-pq', 'Refresco Surtido Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.85, null, 0.0, 5, true, 'BODEGA!B156'),
  ('refresco-surtido-1l', 'Refresco Surtido 1L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.19, null, 0.0, 5, true, 'BODEGA!B157'),
  ('refresco-surtido-1-1-2l', 'Refresco Surtido 1 1/2L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.6, null, 0.0, 5, true, 'BODEGA!B158'),
  ('refresco-surtido-2-l', 'Refresco Surtido 2 L', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 0.0, 5, true, 'BODEGA!B159'),
  ('refresco-glup-pq', 'Refresco Glup Pq', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.53, null, 0.0, 5, true, 'BODEGA!B160'),
  ('refresco-glup-gd', 'Refresco Glup Gd', 'bebidas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.8, null, 0.0, 5, true, 'BODEGA!B161'),
  ('jabon-alive-500g', 'Jabon Alive 500G', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 20.0, 5, true, 'BODEGA!B163'),
  ('jabon-multi-clean-400g', 'Jabon Multi Clean 400G', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 10.0, 5, true, 'BODEGA!B164'),
  ('jabon-las-llaves-panela', 'Jabon Las Llaves Panela', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 16.0, 5, true, 'BODEGA!B165'),
  ('jabon-protex', 'Jabon Protex', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 9.0, 5, true, 'BODEGA!B166'),
  ('jabon-anita-pq', 'Jabon Anita Pq', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'BODEGA!B167'),
  ('jabon-anita', 'Jabon Anita', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.6, null, 1.0, 5, true, 'BODEGA!B168'),
  ('cloro', 'Cloro', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 8.0, 5, true, 'BODEGA!B169'),
  ('desinfectante-oso', 'Desinfectante Oso', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 12.0, 5, true, 'BODEGA!B170'),
  ('suavitel-alive', 'Suavitel Alive', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.8, null, 15.0, 5, true, 'BODEGA!B171'),
  ('lavaplatos-premio', 'Lavaplatos Premio', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 17.0, 5, true, 'BODEGA!B172'),
  ('lavaplatos-liquido-oso', 'Lavaplatos Liquido Oso', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.62, null, 12.0, 5, true, 'BODEGA!B173'),
  ('lavaplatos-liquido-kris', 'Lavaplatos Liquido Kris', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.36, null, 5.0, 5, true, 'BODEGA!B174'),
  ('papel-alisoft-verde', 'Papel Alisoft Verde', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.8, null, 0.0, 5, true, 'BODEGA!B175'),
  ('papel-alisoft', 'Papel Alisoft', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 0.0, 5, true, 'BODEGA!B176'),
  ('papel-alisoft-und', 'Papel Alisoft Und', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.29, null, 0.0, 5, true, 'BODEGA!B177'),
  ('papel-euro', 'Papel Euro', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.2, null, 11.0, 5, true, 'BODEGA!B178'),
  ('papel-caricias', 'Papel Caricias', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 0.0, 5, true, 'BODEGA!B179'),
  ('panal-baby-finger', 'Pañal Baby Finger', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.0, null, 4.0, 5, true, 'BODEGA!B180'),
  ('panal-hugme-und', 'Pañal Hugme Und', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.4, null, 2.0, 5, true, 'BODEGA!B181'),
  ('toallas-humedas-pq', 'Toallas Humedas Pq', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.42, null, 5.0, 5, true, 'BODEGA!B182'),
  ('toallas-humedas-gd', 'Toallas Humedas Gd', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 0.0, 5, true, 'BODEGA!B183'),
  ('toallas-sanitarias-larga', 'Toallas Sanitarias Larga', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.45, null, 0.0, 5, true, 'BODEGA!B184'),
  ('toallas-sanitarias-noche', 'Toallas Sanitarias Noche', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.33, null, 0.0, 5, true, 'BODEGA!B185'),
  ('toallas-sanitarias-dia', 'Toallas Sanitarias Dia', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.33, null, 21.0, 5, true, 'BODEGA!B186'),
  ('toallas-sanitarias-detall', 'Toallas Sanitarias Detall', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.2, null, 0.0, 5, true, 'BODEGA!B187'),
  ('protector-diario-toallitas', 'Protector Diario Toallitas', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 0.0, 5, true, 'BODEGA!B188'),
  ('crema-colgate', 'Crema Colgate', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 6.0, 5, true, 'BODEGA!B189'),
  ('crema-alident', 'Crema Alident', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 7.0, 5, true, 'BODEGA!B190'),
  ('crema-corporal-every-n', 'Crema Corporal Every N', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 6.5, null, 0.0, 5, true, 'BODEGA!B191'),
  ('shampoo-every-night', 'Shampoo Every Night', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 6.3, null, 0.0, 5, true, 'BODEGA!B192'),
  ('shampoo-alive', 'Shampoo Alive', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.0, null, 7.0, 5, true, 'BODEGA!B193'),
  ('shampoo-sobre', 'Shampoo Sobre', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.53, null, 7.0, 5, true, 'BODEGA!B194'),
  ('shampoo-nutribella', 'Shampoo Nutribella', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.57, null, 12.0, 5, true, 'BODEGA!B195'),
  ('nutribella-sobre', 'Nutribella Sobre', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.9, null, 0.0, 5, true, 'BODEGA!B196'),
  ('acondicionador-sobre', 'Acondicionador Sobre', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.53, null, 10.0, 5, true, 'BODEGA!B197'),
  ('gelatina-rolda-pq', 'Gelatina Rolda Pq', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 2.0, 5, true, 'BODEGA!B198'),
  ('gelatina-rolda-g', 'Gelatina Rolda G', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.5, null, 3.0, 5, true, 'BODEGA!B199'),
  ('gelatina-adi-pq', 'Gelatina Adi Pq', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 0.0, 5, true, 'BODEGA!B200'),
  ('desodorante', 'Desodorante', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.2, null, 6.0, 5, true, 'BODEGA!B201'),
  ('desodorante-sobre', 'Desodorante Sobre', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.59, null, 53.0, 5, true, 'BODEGA!B202'),
  ('afeitadora-dama', 'Afeitadora Dama', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.12, null, 5.0, 5, true, 'BODEGA!B203'),
  ('afeitadora-caballero', 'Afeitadora Caballero', 'higiene-y-limpieza', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.1, null, 6.0, 5, true, 'BODEGA!B204'),
  ('esponja', 'Esponja', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.7, null, 3.0, 5, true, 'BODEGA!B206'),
  ('esponja-de-brillo', 'Esponja De Brillo', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.68, null, 0.0, 5, true, 'BODEGA!B207'),
  ('pega-loka', 'Pega Loka', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.78, null, 18.0, 5, true, 'BODEGA!B208'),
  ('vela', 'Vela', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.29, null, 0.0, 5, true, 'BODEGA!B209'),
  ('bombillo-9w', 'Bombillo 9W', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'BODEGA!B210'),
  ('bombillo-12w', 'Bombillo 12W', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.3, null, 0.0, 5, true, 'BODEGA!B211'),
  ('bombillo-15w', 'Bombillo 15W', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.4, null, 15.0, 5, true, 'BODEGA!B212'),
  ('tabaco', 'Tabaco', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.35, null, 43.0, 5, true, 'BODEGA!B213'),
  ('papel-de-aluminio', 'Papel De Aluminio', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.43, null, 10.0, 5, true, 'BODEGA!B214'),
  ('hojillas', 'Hojillas', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.56, null, 7.0, 5, true, 'BODEGA!B215'),
  ('hojillas-und', 'Hojillas Und', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.23, null, 1.0, 5, true, 'BODEGA!B216'),
  ('paquete-pitillos', 'Paquete Pitillos', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.74, null, 6.0, 5, true, 'BODEGA!B217'),
  ('cepillo-dental', 'Cepillo Dental', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.7, null, 0.0, 5, true, 'BODEGA!B218'),
  ('boligrafo', 'Boligrafo', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.37, null, 0.0, 5, true, 'BODEGA!B219'),
  ('pan-sandw', 'Pan Sandw', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 0.0, 5, true, 'BODEGA!B220'),
  ('pastillas-acetaminofen', 'Pastillas Acetaminofen', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.1, null, 0.0, 5, true, 'BODEGA!B221'),
  ('pastillas-ibuprofeno', 'Pastillas Ibuprofeno', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.12, null, 0.0, 5, true, 'BODEGA!B222'),
  ('yesquero', 'Yesquero', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.25, null, 0.0, 5, true, 'BODEGA!B223'),
  ('chimo', 'Chimo', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.6, null, 0.0, 5, true, 'BODEGA!B224'),
  ('cinta-de-embalaje', 'Cinta De Embalaje', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.69, null, 0.0, 5, true, 'BODEGA!B225'),
  ('vaso', 'Vaso', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.9, null, 0.0, 5, true, 'BODEGA!B226'),
  ('plagatox', 'Plagatox', 'otros-articulos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.25, null, 0.0, 5, true, 'BODEGA!B227'),
  ('club-social', 'Club Social', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.39, null, 0.0, 5, true, 'CHUCHERIA!B5'),
  ('galleta-soda', 'Galleta Soda', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.29, null, 0.0, 5, true, 'CHUCHERIA!B6'),
  ('galleta-saltitacos', 'Galleta Saltitacos', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.63, null, 0.0, 5, true, 'CHUCHERIA!B7'),
  ('galleta-kraker', 'Galleta Kraker', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.49, null, 0.0, 5, true, 'CHUCHERIA!B8'),
  ('maria', 'Maria', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.39, null, 0.0, 5, true, 'CHUCHERIA!B9'),
  ('maria-mini', 'Maria Mini', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.42, null, 0.0, 5, true, 'CHUCHERIA!B10'),
  ('marilu-chocolate', 'Marilu Chocolate', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.59, null, 0.0, 5, true, 'CHUCHERIA!B11'),
  ('marilu-vainilla', 'Marilu Vainilla', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.3, null, 0.0, 5, true, 'CHUCHERIA!B12'),
  ('marilu-tubo', 'Marilu Tubo', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.6, null, 0.0, 5, true, 'CHUCHERIA!B13'),
  ('charmy', 'Charmy', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.23, null, 0.0, 5, true, 'CHUCHERIA!B14'),
  ('chips-ahoy', 'Chips Ahoy', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.68, null, 0.0, 5, true, 'CHUCHERIA!B15'),
  ('oreo-pq', 'Oreo Pq', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.68, null, 0.0, 5, true, 'CHUCHERIA!B16'),
  ('oreo-tubo', 'Oreo Tubo', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.68, null, 0.0, 5, true, 'CHUCHERIA!B17'),
  ('tip-top', 'Tip Top', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B18'),
  ('limon-tv', 'Limon Tv', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B19'),
  ('dani-chips', 'Dani Chips', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.18, null, 0.0, 5, true, 'CHUCHERIA!B20'),
  ('crack-it', 'Crack-It', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.2, null, 0.0, 5, true, 'CHUCHERIA!B21'),
  ('maria-delicia', 'Maria Delicia', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'CHUCHERIA!B22'),
  ('katy', 'Katy', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.81, null, 0.0, 5, true, 'CHUCHERIA!B23'),
  ('galletas-coqui', 'Galletas Coqui', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'CHUCHERIA!B24'),
  ('palmeritas', 'Palmeritas', 'galletas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.33, null, 0.0, 5, true, 'CHUCHERIA!B25'),
  ('wafer-bridge', 'Wafer Bridge', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.45, null, 0.0, 5, true, 'CHUCHERIA!B27'),
  ('mordisquito', 'Mordisquito', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.43, null, 0.0, 5, true, 'CHUCHERIA!B28'),
  ('cocosette', 'Cocosette', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B29'),
  ('susy', 'Susy', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B30'),
  ('flaquito-pq', 'Flaquito Pq', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.23, null, 0.0, 5, true, 'CHUCHERIA!B31'),
  ('flaquito-gd', 'Flaquito Gd', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.69, null, 0.0, 5, true, 'CHUCHERIA!B32'),
  ('pirulin', 'Pirulin', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.7, null, 0.0, 5, true, 'CHUCHERIA!B33'),
  ('piazza', 'Piazza', 'wafers', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.4, null, 0.0, 5, true, 'CHUCHERIA!B34'),
  ('boli-bull-pq', 'Boli Bull Pq', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.39, null, 0.0, 5, true, 'CHUCHERIA!B36'),
  ('boli-bull-familiar', 'Boli Bull Familiar', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.1, null, 0.0, 5, true, 'CHUCHERIA!B37'),
  ('mega-boli-bull-familiar', 'Mega Boli Bull Familiar', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.35, null, 0.0, 5, true, 'CHUCHERIA!B38'),
  ('pepito-pequeno', 'Pepito Pequeño', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.75, null, 0.0, 5, true, 'CHUCHERIA!B39'),
  ('pepito-grande', 'Pepito Grande', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.64, null, 0.0, 5, true, 'CHUCHERIA!B40'),
  ('cheese-bulls', 'Cheese Bulls', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.55, null, 0.0, 5, true, 'CHUCHERIA!B41'),
  ('rikito-queso', 'Rikito Queso', 'snacks', 'bodega'::unidad_negocio, 'KG'::unidad_medida, 1.35, null, 0.0, 1, true, 'CHUCHERIA!B42'),
  ('rikito-picante', 'Rikito Picante', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.35, null, 0.0, 5, true, 'CHUCHERIA!B43'),
  ('cheese-tris-pq', 'Cheese Tris Pq', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.12, null, 0.0, 5, true, 'CHUCHERIA!B44'),
  ('cheese-tris-gd', 'Cheese Tris Gd', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.27, null, 0.0, 5, true, 'CHUCHERIA!B45'),
  ('dorito-pq', 'Dorito Pq', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.35, null, 0.0, 5, true, 'CHUCHERIA!B46'),
  ('dorito-gd', 'Dorito Gd', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.63, null, 0.0, 5, true, 'CHUCHERIA!B47'),
  ('dorito-hot-gd', 'Dorito Hot Gd', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.63, null, 0.0, 5, true, 'CHUCHERIA!B48'),
  ('takis', 'Takis', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.39, null, 0.0, 5, true, 'CHUCHERIA!B49'),
  ('tostitos', 'Tostitos', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.27, null, 0.0, 5, true, 'CHUCHERIA!B50'),
  ('papa-lays', 'Papa Lays', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B51'),
  ('ruffles-pequena', 'Ruffles Pequeña', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.53, null, 0.0, 5, true, 'CHUCHERIA!B52'),
  ('ruffles-grande', 'Ruffles Grande', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.13, null, 0.0, 5, true, 'CHUCHERIA!B53'),
  ('chicharron-criollo', 'Chicharron Criollo', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.1, null, 0.0, 5, true, 'CHUCHERIA!B54'),
  ('natuchip', 'Natuchip', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.0, null, 0.0, 5, true, 'CHUCHERIA!B55'),
  ('tom-aros', 'Tom Aros', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'CHUCHERIA!B56'),
  ('tom-pq', 'Tom Pq', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'CHUCHERIA!B57'),
  ('tom-gd', 'Tom Gd', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.25, null, 0.0, 5, true, 'CHUCHERIA!B58'),
  ('tom-familiar', 'Tom Familiar', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 0.0, 5, true, 'CHUCHERIA!B59'),
  ('palomitas', 'Palomitas', 'snacks', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.45, null, 0.0, 5, true, 'CHUCHERIA!B60'),
  ('nuttelini', 'Nuttelini', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.4, null, 0.0, 5, true, 'CHUCHERIA!B62'),
  ('nucita-tubo', 'Nucita Tubo', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.74, null, 0.0, 5, true, 'CHUCHERIA!B63'),
  ('flips-pq', 'Flips Pq', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.75, null, 0.0, 5, true, 'CHUCHERIA!B64'),
  ('flips-m', 'Flips M', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 0.0, 5, true, 'CHUCHERIA!B65'),
  ('flips-caja', 'Flips Caja', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 4.5, null, 0.0, 5, true, 'CHUCHERIA!B66'),
  ('crunch-lonchera', 'Crunch Lonchera', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.75, null, 0.0, 5, true, 'CHUCHERIA!B67'),
  ('crunch', 'Crunch', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.6, null, 0.0, 5, true, 'CHUCHERIA!B68'),
  ('azucaradas-mini', 'Azucaradas Mini', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'CHUCHERIA!B69'),
  ('mini-brownies', 'Mini Brownies', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.5, null, 0.0, 5, true, 'CHUCHERIA!B70'),
  ('mini-piruetas', 'Mini Piruetas', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 3.06, null, 0.0, 5, true, 'CHUCHERIA!B71'),
  ('samba', 'Samba', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.4, null, 0.0, 5, true, 'CHUCHERIA!B72'),
  ('toronto', 'Toronto', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.78, null, 0.0, 5, true, 'CHUCHERIA!B73'),
  ('palitos', 'Palitos', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.58, null, 0.0, 5, true, 'CHUCHERIA!B74'),
  ('palitos-gd', 'Palitos Gd', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.43, null, 0.0, 5, true, 'CHUCHERIA!B75'),
  ('dandy', 'Dandy', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.87, null, 0.0, 5, true, 'CHUCHERIA!B76'),
  ('stadium', 'Stadium', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.61, null, 0.0, 5, true, 'CHUCHERIA!B77'),
  ('chocolate-galak', 'Chocolate Galak', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.78, null, 0.0, 5, true, 'CHUCHERIA!B78'),
  ('chocolate-leche', 'Chocolate Leche', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.54, null, 0.0, 5, true, 'CHUCHERIA!B79'),
  ('chocolate-cri-cri', 'Chocolate Cri-Cri', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.54, null, 0.0, 5, true, 'CHUCHERIA!B80'),
  ('chocolate-rikiti', 'Chocolate Rikiti', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.54, null, 0.0, 5, true, 'CHUCHERIA!B81'),
  ('huevitos', 'Huevitos', 'chocolates', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.74, null, 0.0, 5, true, 'CHUCHERIA!B82'),
  ('caramelos-fruticas', 'Caramelos Fruticas', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.04, null, 0.0, 5, true, 'CHUCHERIA!B85'),
  ('caramelo-menta', 'Caramelo Menta', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.04, null, 0.0, 5, true, 'CHUCHERIA!B86'),
  ('caramelo-chao', 'Caramelo Chao', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.06, null, 0.0, 5, true, 'CHUCHERIA!B87'),
  ('caramelo-chao-x5', 'Caramelo Chao X5', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.35, null, 0.0, 5, true, 'CHUCHERIA!B88'),
  ('caramelo-miel', 'Caramelo Miel', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.08, null, 0.0, 5, true, 'CHUCHERIA!B89'),
  ('caramelo-bianchi', 'Caramelo Bianchi', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.08, null, 0.0, 5, true, 'CHUCHERIA!B90'),
  ('caramelos-minibum', 'Caramelos Minibum', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.08, null, 0.0, 5, true, 'CHUCHERIA!B91'),
  ('caramelos-freegells', 'Caramelos Freegells', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.37, null, 0.0, 5, true, 'CHUCHERIA!B92'),
  ('caramelos-vitac', 'Caramelos Vitac', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.37, null, 0.0, 5, true, 'CHUCHERIA!B93'),
  ('mentos', 'Mentos', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.59, null, 0.0, 5, true, 'CHUCHERIA!B94'),
  ('chupeta-foot', 'Chupeta Foot', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.15, null, 0.0, 5, true, 'CHUCHERIA!B95'),
  ('chupeta-bon-bon', 'Chupeta Bon Bon', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.2, null, 0.0, 5, true, 'CHUCHERIA!B96'),
  ('chupeta-pin-pop-acida', 'Chupeta Pin Pop Acida', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.39, null, 0.0, 5, true, 'CHUCHERIA!B97'),
  ('chupetagool', 'Chupetagool', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.08, null, 0.0, 5, true, 'CHUCHERIA!B98'),
  ('bubbaloo', 'Bubbaloo', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.58, null, 0.0, 5, true, 'CHUCHERIA!B99'),
  ('lokino', 'Lokiño', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'CHUCHERIA!B100'),
  ('oka-loka-nanos', 'Oka Loka Nanos', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.83, null, 0.0, 5, true, 'CHUCHERIA!B101'),
  ('oka-loka', 'Oka Loka', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.48, null, 0.0, 5, true, 'CHUCHERIA!B102'),
  ('mechas-lokas', 'Mechas Lokas', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 0.0, 5, true, 'CHUCHERIA!B103'),
  ('car-candy', 'Car Candy', 'caramelos', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.7, null, 0.0, 5, true, 'CHUCHERIA!B104'),
  ('chicle-bola-acido', 'Chicle Bola Acido', 'chicles', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.39, null, 0.0, 5, true, 'CHUCHERIA!B106'),
  ('agogo', 'Agogo', 'chicles', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.29, null, 0.0, 5, true, 'CHUCHERIA!B107'),
  ('tutim', 'Tutim', 'chicles', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.21, null, 0.0, 5, true, 'CHUCHERIA!B108'),
  ('chicle-freegells', 'Chicle Freegells', 'chicles', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.5, null, 0.0, 5, true, 'CHUCHERIA!B109'),
  ('gomitas-gummy-roli', 'Gomitas Gummy Roli', 'gomitas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.94, null, 0.0, 5, true, 'CHUCHERIA!B111'),
  ('gomitas-grissly', 'Gomitas Grissly', 'gomitas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'CHUCHERIA!B112'),
  ('gomitas-trululu-und', 'Gomitas Trululu Und', 'gomitas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.12, null, 0.0, 5, true, 'CHUCHERIA!B113'),
  ('crismelos-mini', 'Crismelos Mini', 'gomitas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.61, null, 0.0, 5, true, 'CHUCHERIA!B114'),
  ('marshmallows', 'Marshmallows', 'gomitas', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.5, null, 0.0, 5, true, 'CHUCHERIA!B115'),
  ('panque-once-once', 'Panque Once Once', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.53, null, 0.0, 5, true, 'CHUCHERIA!B118'),
  ('panque-fudge', 'Panque Fudge', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.82, null, 0.0, 5, true, 'CHUCHERIA!B119'),
  ('botecito', 'Botecito', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.0, null, 0.0, 5, true, 'CHUCHERIA!B120'),
  ('torta-de-manzana', 'Torta De Manzana', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.88, null, 0.0, 5, true, 'CHUCHERIA!B121'),
  ('brownies', 'Brownies', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 2.0, null, 0.0, 5, true, 'CHUCHERIA!B122'),
  ('alfajol', 'Alfajol', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 1.38, null, 0.0, 5, true, 'CHUCHERIA!B123'),
  ('catalina', 'Catalina', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.38, null, 0.0, 5, true, 'CHUCHERIA!B124'),
  ('bocadillo-guayaba-plata', 'Bocadillo Guayaba / Plata', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.26, null, 0.0, 5, true, 'CHUCHERIA!B125'),
  ('mani-bokas', 'Mani Bokas', 'tortas-y-panques', 'bodega'::unidad_negocio, 'UND'::unidad_medida, 0.75, null, 0.0, 5, true, 'CHUCHERIA!B126')
on conflict (sku) do update set
  nombre = excluded.nombre,
  categoria_id = excluded.categoria_id,
  precio_venta_usd = excluded.precio_venta_usd,
  stock_minimo = excluded.stock_minimo,
  unidad_medida = excluded.unidad_medida;

-- === 04-tasa-y-moneda ===

insert into public.tasa_cambio (valor, nota)
select 800.0, 'seed inicial (BODEGA!G2)'
where not exists (select 1 from public.tasa_cambio);

